In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('./../data/ai-productivity-data/user_level_ai_adoption.csv')

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    15000 non-null  object
 1   Industry                   15000 non-null  object
 2   Job_Role                   15000 non-null  object
 3   Location                   15000 non-null  object
 4   Experience_Years           15000 non-null  int64
 5   Primary_AI_Tool            15000 non-null  object
 6   Daily_Token_Usage          15000 non-null  int64
 7   Tasks_Automated_Per_Week   15000 non-null  int64
 8   Productivity_Gain_Percent  15000 non-null  float64
 9   Adoption_Date              15000 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 1.1+ MB

In [4]:
df1.head()

,User_ID,Industry,Job_Role,Location,Experience_Years,Primary_AI_Tool,Daily_Token_Usage,Tasks_Automated_Per_Week,Productivity_Gain_Percent,Adoption_Date
0,USR-690F519F,Software Development,Software Engineer,Europe,13,ChatGPT (OpenAI),10640,2,19.3,2023-02-28
1,USR-72A07ABB,Software Development,Software Engineer,North America,9,Claude (Anthropic),8535,1,5.0,2023-08-17
2,USR-CBCEAA19,Finance,Accountant,Asia-Pacific,21,Claude (Anthropic),9585,1,13.4,2023-11-02
3,USR-03B7DC34,Healthcare,Clinical Admin,North America,20,Perplexity,7094,2,9.9,2025-06-06
4,USR-CA8308D1,Marketing,Social Media Manager,Asia-Pacific,14,ChatGPT (OpenAI),9277,1,12.8,2023-04-03

In [5]:
df1['Adoption_Date']=pd.to_datetime(df1['Adoption_Date']);
df1['Adoption_Date'].head()

0   2023-02-28
1   2023-08-17
2   2023-11-02
3   2025-06-06
4   2023-04-03
Name: Adoption_Date, dtype: datetime64[ns]

In [6]:
df1=df1.sort_values('Adoption_Date').reset_index(drop=True)

In [7]:
df1.head()

,User_ID,Industry,Job_Role,Location,Experience_Years,Primary_AI_Tool,Daily_Token_Usage,Tasks_Automated_Per_Week,Productivity_Gain_Percent,Adoption_Date
0,USR-155B3993,Education,Student,Asia-Pacific,1,Claude (Anthropic),4550,1,6.9,2021-01-01
1,USR-8545095D,Software Development,QA Tester,Europe,18,Claude (Anthropic),15953,2,28.8,2021-01-01
2,USR-85C719CE,Software Development,Software Engineer,North America,21,Claude (Anthropic),3498,2,4.9,2021-01-01
3,USR-D3BB4628,Education,Teacher,Asia-Pacific,22,Claude (Anthropic),15637,1,14.3,2021-01-01
4,USR-2C474BB8,Creative & Design,Video Editor,North America,16,Claude (Anthropic),11375,2,23.9,2021-01-01

In [8]:
df1['Productivity_Gain_Percent'].unique()

array([ 6.9, 28.8,  4.9, 14.3, 23.9, 12.9, 19. ,  6.5,  3. , 13.1,  5.7,
        3.4,  2.8,  6. , 12.8, 12.1,  1. ,  9.9, 20.3, 11.3,  2. ,  7.6,
       21.6,  7.8, 48.3, 33.3,  4. ,  7. , 27. ,  8. , 13.8, 51.6,  6.4,
       13. ,  1.5,  1.1,  9.8,  5. ,  2.4, 36.3, 10.3,  7.4,  3.2,  3.9,
       24.6, 11.9, 21.4, 11. ,  8.2,  2.9,  1.6, 20.1, 18.9, 15.5,  5.5,
       10.4,  7.9,  2.6,  8.3, 10.7, 10. , 24.2,  3.3, 10.9, 25.1,  7.7,
       11.2, 14.5, 10.1,  0.6, 21.1,  9. , 17.1, 25. , 16.3,  4.4, 12. ,
        6.6,  8.6, 11.7,  1.9,  4.5, 21.5,  1.4, 48.1,  2.7,  9.2,  5.3,
        8.7, 19.3,  8.9,  5.2,  3.6, 15. , 16.5,  7.2,  7.3, 22.7,  2.2,
       13.6, 23.2, 14.2,  2.5, 11.4, 11.8,  6.8,  4.3, 16.8, 19.1,  8.8,
        0.8, 18.2, 47.9,  9.7,  5.8, 17.3,  7.5,  6.3, 23.6, 10.6, 13.2,
       35.2, 11.5, 38.1,  1.2,  1.7,  3.1,  5.4, 14.6, 11.1,  6.2, 14.1,
        4.7,  9.5, 40.3,  4.1,  7.1,  8.1, 10.8, 23.5, 32.5,  5.9, 24. ,
       16.7, 22.5, 17.2, 34.9, 10.5, 12.6, 23.8, 13.3,  9.3,  9.6, 22.4,
       15.3,  2.1,  0.9,  1.3,  0.7, 22.8, 24.8, 22.6, 11.6,  4.2, 17. ,
       15.2, 62.4, 36.6, 12.5,  5.6, 16.4, 61.6, 12.3, 16.9, 10.2, 41.8,
        8.4,  6.7, 17.4, 17.6, 20.4,  5.1,  1.8, 16.2, 18.8,  9.1, 12.4,
       17.5, 50.1, 21.2, 13.5, 18.5, 37.7, 14. , 16. , 69.9, 14.7, 26.8,
       59.9,  2.3, 13.7, 53. , 28.2, 33. ,  3.7, 14.8, 20.8,  0.4,  3.5,
        3.8,  6.1,  0.5, 23. , 70.1, 20.6, 26.7, 43.4, 68.4, 12.2, 14.4,
       35.5, 26.6, 79.7, 19.5, 19.6, 36.1, 22.2,  4.6, 19.8, 18.3, 60.4,
       19.7, 28. , 23.4, 41.4, 27.4, 21.9, 45. , 18.6, 23.7, 20.7, 27.2,
       18. , 62.2, 42.4, 29.8, 24.7, 20.2, 27.6, 13.4, 20.9, 21.3, 20.5,
       24.1, 22.9, 28.7, 22.1, 17.9, 33.6,  9.4, 26.1, 51.4, 19.4,  4.8,
        8.5, 13.9, 45.3, 17.7, 36.2, 56. , 28.4, 24.5, 21. , 20. , 17.8,
       33.8, 15.4, 37.1, 25.6, 66.5, 31. , 15.9, 16.1, 15.6, 78.6, 12.7,
       56.2, 21.7, 30.7, 18.1, 29.9, 28.6, 41.7, 15.8, 31.4, 23.1, 42.2,
       75.4, 66.9, 18.7, 72.6, 46.2, 32.4, 16.6, 19.2, 14.9, 32.3, 41.6,
       26.2, 47.3, 25.3, 27.3, 55.2, 27.9, 24.3, 38.4, 28.9, 34.1, 25.9,
       30.1, 73.7, 50.6, 69.5, 82.1, 75.5, 15.1, 35.9, 21.8, 61.7, 31.8,
       78.3, 61.1, 32.2, 29.7, 67.8, 41.2, 18.4, 71.8, 49. , 67.1, 79.6,
       76.6, 45.8, 76.2, 31.5, 36.4, 71.2, 83.5, 62. , 26.9, 40.4, 15.7,
        0.3, 22. , 31.2, 64.7, 36.9, 26.5, 46.5, 27.7, 38. , 27.8, 28.1,
       29. , 70.2, 51.9, 30.8, 32.6, 77.8, 23.3, 33.2, 29.5, 24.9, 38.2,
       49.5, 59.6, 25.2, 38.6, 59.7, 69.3, 43.8, 31.1, 42.7, 24.4, 30.3,
       39.9, 82.3, 45.2, 28.5, 26.4, 56.3, 74.4, 76.1, 78.1, 44.1, 49.4,
       27.5, 22.3, 25.8, 41.3, 67.3, 58.1, 34.8, 19.9, 74.1, 35.1, 26.3,
       83.8, 65.4, 44.5, 34.7, 34.5, 42.3, 46.9, 64.1, 63.3, 62.3, 52.2,
       84.8, 37.4, 29.4, 52.5, 51.5, 73.2, 30.4, 44.3, 25.7, 45.4, 76. ,
       34. , 47.1, 34.4, 34.2, 44.2, 58.6, 73. , 36.7, 36.8, 59.4, 69.2,
       49.9, 25.5, 30. , 48.8, 49.7, 60.7, 67. , 57.8, 42.6, 43.5, 54.9,
       45.7, 32.8, 50.2, 42. , 43.7, 62.9, 67.6, 40.2, 39.4, 66.2, 72.5,
       61. , 43.3, 67.5, 83.3, 40.5, 29.3, 48. , 56.4, 50.8, 43. , 45.9,
       26. , 58.4, 76.4, 38.7, 39. , 25.4, 40. , 33.9, 57.4, 60.5, 28.3,
       31.9, 76.5, 32.9, 82.5, 60.3, 74.3, 65.1, 78.8, 53.8, 71.3, 51.2,
       61.2, 50. , 40.7, 50.5, 46.8, 50.7, 35.7, 55.7, 29.2, 57.5, 42.1,
       61.3, 73.6, 47. , 68.9, 64.8, 43.6, 65.8, 75.1, 41.5, 52.7, 30.6,
       83.6, 66.7, 64.3, 45.5, 58.7, 35.4, 61.9, 39.5, 80.5, 57.7, 44.6,
       37.8, 54.5, 72.9, 34.3, 59.3, 73.3, 50.4, 75. , 40.1, 27.1, 82.2,
       44.4, 49.6, 61.5, 82. , 62.6, 57.9, 69.7, 70.5, 66.3, 31.3, 29.1,
       47.8, 46.7, 52.1, 74. , 76.8, 80. , 77.6, 57.6, 33.5, 39.2, 63.7,
       56.1, 54. , 60.6, 69.4, 33.7, 54.7, 33.4, 60. , 58.2, 84.3, 49.3,
       71.5, 35.3, 54.1, 39.7, 80.6, 34.6, 84.9, 48.2, 67.2, 83.2, 68.6,
       52.4, 45.1, 43.2, 48.7, 57.1, 78.2, 47.5, 60.2, 66.1, 54.6, 52.9,
       75.6, 47.6, 37.2, 51. , 30.2, 82.8, 73.5, 32.1, 54.3, 71.9, 75.9,
       42.8, 73.9, 56.7, 39.3, 55.8, 71.7, 47.2, 37.9, 38.9, 66.6, 67.4,
       55.5, 46.3, 59.1, 35.8, 33.1, 68.8, 51.1, 37.5, 64.5, 51.3, 39.1,
       42.9, 60.8, 64.4, 44.8, 54.2, 41. , 32.7, 37.3, 36.5, 70.8, 81.4,
       70.6, 32. , 49.1, 37. , 53.1, 37.6, 31.6, 30.9, 80.4, 62.5, 48.5,
       38.8, 71.1, 84.1, 31.7, 50.3, 69.6, 50.9, 43.1, 45.6, 81. , 79.4,
       42.5, 63.4, 36. , 72.7, 35.6, 55.4])

In [9]:
df1['Adoption_Date'].unique()

<DatetimeArray>
['2021-01-01 00:00:00', '2021-01-02 00:00:00', '2021-01-03 00:00:00',
 '2021-01-04 00:00:00', '2021-01-05 00:00:00', '2021-01-06 00:00:00',
 '2021-01-07 00:00:00', '2021-01-09 00:00:00', '2021-01-10 00:00:00',
 '2021-01-11 00:00:00',
 ...
 '2026-06-21 00:00:00', '2026-06-22 00:00:00', '2026-06-23 00:00:00',
 '2026-06-24 00:00:00', '2026-06-25 00:00:00', '2026-06-26 00:00:00',
 '2026-06-27 00:00:00', '2026-06-28 00:00:00', '2026-06-29 00:00:00',
 '2026-06-30 00:00:00']
Length: 1940, dtype: datetime64[ns]

In [10]:
df1.head()

,User_ID,Industry,Job_Role,Location,Experience_Years,Primary_AI_Tool,Daily_Token_Usage,Tasks_Automated_Per_Week,Productivity_Gain_Percent,Adoption_Date
0,USR-155B3993,Education,Student,Asia-Pacific,1,Claude (Anthropic),4550,1,6.9,2021-01-01
1,USR-8545095D,Software Development,QA Tester,Europe,18,Claude (Anthropic),15953,2,28.8,2021-01-01
2,USR-85C719CE,Software Development,Software Engineer,North America,21,Claude (Anthropic),3498,2,4.9,2021-01-01
3,USR-D3BB4628,Education,Teacher,Asia-Pacific,22,Claude (Anthropic),15637,1,14.3,2021-01-01
4,USR-2C474BB8,Creative & Design,Video Editor,North America,16,Claude (Anthropic),11375,2,23.9,2021-01-01

In [11]:
##df1.to_csv('./../data/ai-productivity-data/cleaned_user_level_ai_adoption.csv', index=False)

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    15000 non-null  object
 1   Industry                   15000 non-null  object
 2   Job_Role                   15000 non-null  object
 3   Location                   15000 non-null  object
 4   Experience_Years           15000 non-null  int64
 5   Primary_AI_Tool            15000 non-null  object
 6   Daily_Token_Usage          15000 non-null  int64
 7   Tasks_Automated_Per_Week   15000 non-null  int64
 8   Productivity_Gain_Percent  15000 non-null  float64
 9   Adoption_Date              15000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), object(5)
memory usage: 1.1+ MB