In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('./../data/ai-productivity-data/user_level_ai_adoption.csv')

In [15]:
df2=pd.read_csv('./../data/ai-productivity-data/ai_adoption_productivity_2021_2026.csv')

In [4]:
df1.head()

,User_ID,Industry,Job_Role,Location,Experience_Years,Primary_AI_Tool,Daily_Token_Usage,Tasks_Automated_Per_Week,Productivity_Gain_Percent,Adoption_Date
0,USR-690F519F,Software Development,Software Engineer,Europe,13,ChatGPT (OpenAI),10640,2,19.3,2023-02-28
1,USR-72A07ABB,Software Development,Software Engineer,North America,9,Claude (Anthropic),8535,1,5.0,2023-08-17
2,USR-CBCEAA19,Finance,Accountant,Asia-Pacific,21,Claude (Anthropic),9585,1,13.4,2023-11-02
3,USR-03B7DC34,Healthcare,Clinical Admin,North America,20,Perplexity,7094,2,9.9,2025-06-06
4,USR-CA8308D1,Marketing,Social Media Manager,Asia-Pacific,14,ChatGPT (OpenAI),9277,1,12.8,2023-04-03

In [16]:
df2.head()

,YearMonth,Industry,Primary Use Case,Global Active Users (Millions),Average Tokens/User/Day,Productivity Gain (%)
0,2021-01,Software Development,Code Generation & Debugging,0.49,5248,4.9
1,2021-01,Marketing & Content,Copywriting & SEO,1.24,2141,9.7
2,2021-01,Customer Support,Automated Chatbots & Triage,0.83,3206,15.5
3,2021-01,Healthcare,Medical Records & Diagnostics Assistance,0.10,937,1.9
4,2021-01,Education,Lesson Planning & Tutoring,0.39,1594,7.6

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    15000 non-null  object
 1   Industry                   15000 non-null  object
 2   Job_Role                   15000 non-null  object
 3   Location                   15000 non-null  object
 4   Experience_Years           15000 non-null  int64
 5   Primary_AI_Tool            15000 non-null  object
 6   Daily_Token_Usage          15000 non-null  int64
 7   Tasks_Automated_Per_Week   15000 non-null  int64
 8   Productivity_Gain_Percent  15000 non-null  float64
 9   Adoption_Date              15000 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 1.1+ MB

In [18]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 402 entries, 0 to 401
Data columns (total 6 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   YearMonth                       402 non-null    object
 1   Industry                        402 non-null    object
 2   Primary Use Case                402 non-null    object
 3   Global Active Users (Millions)  402 non-null    float64
 4   Average Tokens/User/Day         402 non-null    int64
 5   Productivity Gain (%)           402 non-null    float64
dtypes: float64(2), int64(1), object(3)
memory usage: 19.0+ KB

In [19]:
df1.describe()

,Experience_Years,Daily_Token_Usage,Tasks_Automated_Per_Week,Productivity_Gain_Percent
count,15000.000000,15000.000000,15000.000000,15000.000000
mean,13.013400,8958.312200,1.913267,11.215827
std,7.215642,8449.890624,1.176196,11.578100
min,1.000000,411.000000,1.000000,0.300000
25%,7.000000,3049.000000,1.000000,3.600000
50%,13.000000,7336.000000,2.000000,8.100000
75%,19.000000,11740.250000,3.000000,14.800000
max,25.000000,58989.000000,12.000000,84.900000

In [20]:
df2.describe()

,Global Active Users (Millions),Average Tokens/User/Day,Productivity Gain (%)
count,402.000000,402.000000,402.000000
mean,18.089229,11732.104478,41.005224
std,26.138400,16189.762385,15.473256
min,0.100000,935.000000,1.900000
25%,1.007500,3287.750000,30.225000
50%,5.240000,6456.000000,41.300000
75%,29.170000,12103.750000,52.300000
max,103.970000,100750.000000,71.100000

In [21]:
df1.isnull().sum()

User_ID                      0
Industry                     0
Job_Role                     0
Location                     0
Experience_Years             0
Primary_AI_Tool              0
Daily_Token_Usage            0
Tasks_Automated_Per_Week     0
Productivity_Gain_Percent    0
Adoption_Date                0
dtype: int64

In [22]:
df2.isnull().sum()

YearMonth                         0
Industry                          0
Primary Use Case                  0
Global Active Users (Millions)    0
Average Tokens/User/Day           0
Productivity Gain (%)             0
dtype: int64

In [23]:
df1.duplicated().sum()

0

In [24]:
df2.duplicated().sum()

0